<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
            table, form {
                width: 100%;
                max-width: 600px;
                margin: 40px auto;
            }
            form input, .btn {
                display: block;
                padding: 20px;
                border-radius: 10px;
                border: 1px solid #ccc;
                width: 80%;
                margin: 10px 0;
                margin: 35px auto;
            }
            form input[type="submit"], .btn {
                cursor: pointer;
                color: #fff;
                background-color: black;
            }
        </style>
    </head>
    <body>
        <h1>Slim</h1>
        <div>a microframework for PHP</div>

        <table>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Remover</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($users as $user): ?>
                <tr>
                    <td><?php echo $user->id; ?></td>
                    <td><?php echo $user->nome; ?></td>
                    <td><?php echo $user->email; ?></td>
                    <td><a href="/users/<?php echo $user->id; ?>" class="btn">Remover</a></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <form class="" action="/users" method="post">
            <legend>Adicionar Novo Usuário</legend>
            <input type="text" name="name" value="" placeholder="Nome do Usuário">
            <input type="email" name="email" value="" placeholder="E-mail do Usuário">
            <input type="password" name="password" value="" placeholder="Senha do Usuário">
            <input type="submit" value="Salvar" />
        </form>
    </body>
</html>
